### ISSUE TITLE
Jetbrains IDE bin pakages complaining of preserved-rebuild

### ISSUE THREAD

**Issue by bsagal** [bombo82/bombo82-overlay#18]
after unmerging libraries i am getting the following message from portage:
```
!!! existing preserved libs:
>>> package: sys-libs/libselinux-3.5-r1
 *  - /lib64/libselinux.so.1
 *      used by /opt/datagrip-2023.2.1/plugins/remote-dev-server/selfcontained/bin/Xvfb (dev-util/datagrip-2023.2.1)
 *      used by /opt/datagrip-2023.2.1/plugins/remote-dev-server/selfcontained/lib/libgio-2.0.so.0 (dev-util/datagrip-2023.2.1)
 *      used by /opt/datagrip-2023.2.1/plugins/remote-dev-server/selfcontained/lib/libglapi.so.0 (dev-util/datagrip-2023.2.1)
 *      used by 12 other files
>>> package: sys-process/audit-3.1.1
 *  - /lib64/libaudit.so.1
 *  - /lib64/libaudit.so.1.0.0
 *      used by /opt/datagrip-2023.2.1/plugins/remote-dev-server/selfcontained/bin/Xvfb (dev-util/datagrip-2023.2.1)
 *      used by /opt/idea-ultimate-2023.2.1/plugins/remote-dev-server/selfcontained/bin/Xvfb (dev-util/idea-ultimate-2023.2.1)
```

I do see not dependency from datagrip or idea-ultimate ebuild on the above libraries.

**Comment by bombo82** [comment]
I added the missing dependencies.

**Comment by Arnvidr** [comment]
Could this be put behind a USE or something I wonder? I've never had these installed, so whatever they're needed for I don't use. The remote-dev-server in the output links to systemd as well, which I also don't have, so it seems fine to discover on its own which options exists for it to use. I'll be happy to have a 'server' USE or similar, as the inode64-overlay seems to have gone with, referencing this issue.

**Comment by bombo82** [comment]
I considered using a USE flag, but I prefer to leave intact the package originally distributed by JetBrains.

These are binary packages and when files within it are removed or modified there could be unpredicatable side effects.
I had bad experiences due to deletion of some files and currently I do not have the time or resources to deal with these complications. The two packages are small, their build fast and they are low risk from a security point of view, so I don't see a big issue installing them, even I would prefer not to install unused packages.

**Comment by Arnvidr** [comment]
That's your privilege of course. Having used this for years without these packages I prefer to create my own ebuild then, to avoid these, as well as systemd if you ever decided to specify all the dependencies.

I hadn't considered deleting any files, much harder to figure out what's wrong then if anything breaks.
